# coding: utf-8

"""
    Manticore Search Client

    Сlient for Manticore Search. 

    The version of the OpenAPI document: 5.0.0
    Contact: info@manticoresearch.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from manticoresearch.models.equals_filter import EqualsFilter
from manticoresearch.models.geo_filter import GeoFilter
from manticoresearch.models.in_filter import InFilter
from manticoresearch.models.range_filter import RangeFilter
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ATTRFILTER_ONE_OF_SCHEMAS = ["EqualsFilter", "GeoFilter", "InFilter", "RangeFilter"]

class AttrFilter(BaseModel):
    """
    AttrFilter
    """
    # data type: EqualsFilter
    oneof_schema_1_validator: Optional[EqualsFilter] = None
    # data type: InFilter
    oneof_schema_2_validator: Optional[InFilter] = None
    # data type: RangeFilter
    oneof_schema_3_validator: Optional[RangeFilter] = None
    # data type: GeoFilter
    oneof_schema_4_validator: Optional[GeoFilter] = None
    actual_instance: Optional[Union[EqualsFilter, GeoFilter, InFilter, RangeFilter]] = None
    one_of_schemas: Set[str] = { "EqualsFilter", "GeoFilter", "InFilter", "RangeFilter" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AttrFilter.model_construct()
        error_messages = []
        match = 0
        # validate data type: EqualsFilter
        if not isinstance(v, EqualsFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EqualsFilter`")
        else:
            match += 1
        # validate data type: InFilter
        if not isinstance(v, InFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `InFilter`")
        else:
            match += 1
        # validate data type: RangeFilter
        if not isinstance(v, RangeFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RangeFilter`")
        else:
            match += 1
        # validate data type: GeoFilter
        if not isinstance(v, GeoFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GeoFilter`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AttrFilter with oneOf schemas: EqualsFilter, GeoFilter, InFilter, RangeFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AttrFilter with oneOf schemas: EqualsFilter, GeoFilter, InFilter, RangeFilter. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into EqualsFilter
        try:
            instance.actual_instance = EqualsFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into InFilter
        try:
            instance.actual_instance = InFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RangeFilter
        try:
            instance.actual_instance = RangeFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GeoFilter
        try:
            instance.actual_instance = GeoFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AttrFilter with oneOf schemas: EqualsFilter, GeoFilter, InFilter, RangeFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AttrFilter with oneOf schemas: EqualsFilter, GeoFilter, InFilter, RangeFilter. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], EqualsFilter, GeoFilter, InFilter, RangeFilter]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


