# coding: utf-8

"""
    Manticore Search Client

    Сlient for Manticore Search. 

    The version of the OpenAPI document: 5.0.0
    Contact: info@manticoresearch.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from manticoresearch.models.match_all_filter import MatchAllFilter
from manticoresearch.models.match_filter import MatchFilter
from manticoresearch.models.match_phrase_filter import MatchPhraseFilter
from manticoresearch.models.query_string_filter import QueryStringFilter
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FULLTEXTFILTER_ONE_OF_SCHEMAS = ["MatchAllFilter", "MatchFilter", "MatchPhraseFilter", "QueryStringFilter"]

class FulltextFilter(BaseModel):
    """
    FulltextFilter
    """
    # data type: MatchFilter
    oneof_schema_1_validator: Optional[MatchFilter] = None
    # data type: MatchAllFilter
    oneof_schema_2_validator: Optional[MatchAllFilter] = None
    # data type: MatchPhraseFilter
    oneof_schema_3_validator: Optional[MatchPhraseFilter] = None
    # data type: QueryStringFilter
    oneof_schema_4_validator: Optional[QueryStringFilter] = None
    actual_instance: Optional[Union[MatchAllFilter, MatchFilter, MatchPhraseFilter, QueryStringFilter]] = None
    one_of_schemas: Set[str] = { "MatchAllFilter", "MatchFilter", "MatchPhraseFilter", "QueryStringFilter" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = FulltextFilter.model_construct()
        error_messages = []
        match = 0
        # validate data type: MatchFilter
        if not isinstance(v, MatchFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MatchFilter`")
        else:
            match += 1
        # validate data type: MatchAllFilter
        if not isinstance(v, MatchAllFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MatchAllFilter`")
        else:
            match += 1
        # validate data type: MatchPhraseFilter
        if not isinstance(v, MatchPhraseFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MatchPhraseFilter`")
        else:
            match += 1
        # validate data type: QueryStringFilter
        if not isinstance(v, QueryStringFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryStringFilter`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FulltextFilter with oneOf schemas: MatchAllFilter, MatchFilter, MatchPhraseFilter, QueryStringFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FulltextFilter with oneOf schemas: MatchAllFilter, MatchFilter, MatchPhraseFilter, QueryStringFilter. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into MatchFilter
        try:
            instance.actual_instance = MatchFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MatchAllFilter
        try:
            instance.actual_instance = MatchAllFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MatchPhraseFilter
        try:
            instance.actual_instance = MatchPhraseFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryStringFilter
        try:
            instance.actual_instance = QueryStringFilter.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FulltextFilter with oneOf schemas: MatchAllFilter, MatchFilter, MatchPhraseFilter, QueryStringFilter. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FulltextFilter with oneOf schemas: MatchAllFilter, MatchFilter, MatchPhraseFilter, QueryStringFilter. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MatchAllFilter, MatchFilter, MatchPhraseFilter, QueryStringFilter]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


