# coding: utf-8

"""
    Manticore Search Client

    Сlient for Manticore Search. 

    The version of the OpenAPI document: 5.0.0
    Contact: info@manticoresearch.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from manticoresearch.models.attr_filter import AttrFilter
from manticoresearch.models.fulltext_filter import FulltextFilter
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

QUERYFILTER_ANY_OF_SCHEMAS = ["AttrFilter", "BoolFilter", "FulltextFilter"]

class QueryFilter(BaseModel):
    """
    QueryFilter
    """

    # data type: AttrFilter
    anyof_schema_1_validator: Optional[AttrFilter] = None
    # data type: BoolFilter
    anyof_schema_2_validator: Optional[BoolFilter] = None
    # data type: FulltextFilter
    anyof_schema_3_validator: Optional[FulltextFilter] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[AttrFilter, BoolFilter, FulltextFilter]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "AttrFilter", "BoolFilter", "FulltextFilter" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = QueryFilter.model_construct()
        error_messages = []
        # validate data type: AttrFilter
        if not isinstance(v, AttrFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AttrFilter`")
        else:
            return v

        # validate data type: BoolFilter
        if not isinstance(v, BoolFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BoolFilter`")
        else:
            return v

        # validate data type: FulltextFilter
        if not isinstance(v, FulltextFilter):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FulltextFilter`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in QueryFilter with anyOf schemas: AttrFilter, BoolFilter, FulltextFilter. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[AttrFilter] = None
        try:
            instance.actual_instance = AttrFilter.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[BoolFilter] = None
        try:
            instance.actual_instance = BoolFilter.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[FulltextFilter] = None
        try:
            instance.actual_instance = FulltextFilter.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into QueryFilter with anyOf schemas: AttrFilter, BoolFilter, FulltextFilter. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AttrFilter, BoolFilter, FulltextFilter]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from manticoresearch.models.bool_filter import BoolFilter
# TODO: Rewrite to not use raise_errors
QueryFilter.model_rebuild(raise_errors=False)

