# coding: utf-8

"""
    Manticore Search Client

    Contact: info@manticoresearch.com
"""


import pprint
import re  # noqa: F401

import six

from manticoresearch.configuration import Configuration


class SearchResponseHits(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'total': 'int',
        'hits': 'list[object]',
        'aggregations': 'list[object]'
    }

    attribute_map = {
        'total': 'total',
        'hits': 'hits',
        'aggregations': 'aggregations'
    }

    def __init__(self, total=None, hits=None, aggregations=None, local_vars_configuration=None):  # noqa: E501
        """SearchResponseHits - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._total = None
        self._hits = None
        self._aggregations = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if hits is not None:
            self.hits = hits
        if aggregations is not None:
            self.aggregations = aggregations

    @property
    def total(self):
        """Gets the total of this SearchResponseHits.  # noqa: E501


        :return: The total of this SearchResponseHits.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this SearchResponseHits.


        :param total: The total of this SearchResponseHits.  # noqa: E501
        :type total: int
        """

        self._total = total

    @property
    def hits(self):
        """Gets the hits of this SearchResponseHits.  # noqa: E501


        :return: The hits of this SearchResponseHits.  # noqa: E501
        :rtype: list[object]
        """
        return self._hits

    @hits.setter
    def hits(self, hits):
        """Sets the hits of this SearchResponseHits.


        :param hits: The hits of this SearchResponseHits.  # noqa: E501
        :type hits: list[object]
        """

        self._hits = hits

    @property
    def aggregations(self):
        """Gets the aggregations of this SearchResponseHits.  # noqa: E501


        :return: The aggregations of this SearchResponseHits.  # noqa: E501
        :rtype: list[object]
        """
        return self._aggregations

    @aggregations.setter
    def aggregations(self, aggregations):
        """Sets the aggregations of this SearchResponseHits.


        :param aggregations: The aggregations of this SearchResponseHits.  # noqa: E501
        :type aggregations: list[object]
        """

        self._aggregations = aggregations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchResponseHits):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchResponseHits):
            return True

        return self.to_dict() != other.to_dict()
